"use client";

import { useEffect, useState } from "react";

interface FoundContact {
  email: string;
  name?: string;
  company?: string;
  phone?: string;
  title?: string;
  source?: string;
}

export default function FindContactsPage() {
  const [lists, setLists] = useState<any[]>([]);
  const [niche, setNiche] = useState("");
  const [apiKey, setApiKey] = useState("");
  const [count, setCount] = useState(20);
  const [results, setResults] = useState<FoundContact[]>([]);
  const [summary, setSummary] = useState("");
  const [searching, setSearching] = useState(false);
  const [error, setError] = useState("");
  const [selectedList, setSelectedList] = useState("");
  const [importing, setImporting] = useState(false);
  const [importResult, setImportResult] = useState<any>(null);
  const [keySaved, setKeySaved] = useState(false);

  // Load saved API key and lists on mount
  useEffect(() => {
    fetch("/api/marketing/lists").then((r) => r.json()).then(setLists).catch(() => {});
    fetch("/api/marketing/settings")
      .then((r) => r.json())
      .then((data) => {
        if (data.settings?.deepseek_api_key) {
          setApiKey(data.settings.deepseek_api_key);
        }
      })
      .catch(() => {});
  }, []);

  // Save the API key to the server
  const saveApiKey = async (key: string) => {
    try {
      const res = await fetch("/api/marketing/settings", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ settings: { deepseek_api_key: key } }),
      });
      if (res.ok) {
        setKeySaved(true);
        setTimeout(() => setKeySaved(false), 2000);
      }
    } catch {
      // silently fail — the key will still be sent with the request
    }
  };

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    setSearching(true);
    setError("");
    setResults([]);
    setImportResult(null);

    // Persist the API key so the user doesn't have to re-enter it
    await saveApiKey(apiKey);

    try {
      const res = await fetch("/api/marketing/contacts/find", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ niche, api_key: apiKey, count }),
      });
      const data = await res.json();
      if (data.error) { setError(data.error); }
      else { setResults(data.contacts || []); setSummary(data.summary || ""); }
    } catch (err: any) { setError(err.message); }
    setSearching(false);
  };

  const handleImport = async () => {
    if (!selectedList || results.length === 0) return;
    setImporting(true);
    setImportResult(null);
    try {
      const res = await fetch("/api/marketing/contacts/import", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          list_id: selectedList,
          contacts: results.map((c) => ({
            email: c.email,
            name: c.name || "",
            company: c.company || "",
            phone: c.phone || "",
            custom_fields: { title: c.title || "", source: c.source || "" },
          })),
        }),
      });
      const data = await res.json();
      setImportResult(data);
    } catch (err: any) { setError(err.message); }
    setImporting(false);
  };

  return (
    <main className="marketing-content">
      <div className="panel-header-row" style={{ marginBottom: "28px" }}>
        <div className="panel-header-left">
          <div className="panel-icon" style={{ background: "linear-gradient(135deg, rgba(168,85,247,0.2), rgba(168,85,247,0.05))", border: "1px solid rgba(168,85,247,0.15)", color: "#c084fc" }}>
            <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="11" cy="11" r="8" /><line x1="21" y1="21" x2="16.65" y2="16.65" />
            </svg>
          </div>
          <div className="panel-header-text">
            <h1>Find Contacts</h1>
            <p>Discover and import new contacts using AI-powered search</p>
          </div>
        </div>
      </div>

      <div className="card" style={{ marginBottom: "1.5rem", padding: "0.75rem 1rem", background: "#fffbeb", border: "1px solid #fde68a", fontSize: "0.85rem", color: "#92400e" }}>
        <strong>⚠️ AI-Generated Sample Data</strong> — The contacts below are generated by AI based on patterns for your niche. They are <strong>not verified real contacts</strong>. Always verify contact details before importing. Use this as a starting point to build your list.
      </div>

      <form onSubmit={handleSearch} className="card" style={{ marginBottom: "1.5rem" }}>
        <div className="form-group">
          <label>Niche / Description</label>
          <textarea
            value={niche}
            onChange={(e) => setNiche(e.target.value)}
            placeholder="e.g., SaaS founders in the US, real estate agents in Florida, etc."
            required
            style={{ minHeight: "60px" }}
          />
        </div>
        <div className="form-row">
          <div className="form-group" style={{ flex: 1 }}>
            <label>
              DeepSeek API Key
              {keySaved && (
                <span style={{ marginLeft: "8px", fontSize: "0.75rem", color: "#166534" }}>✓ Saved</span>
              )}
            </label>
            <input type="password" value={apiKey} onChange={(e) => { setApiKey(e.target.value); setKeySaved(false); }} required placeholder="sk-..." />
          </div>
          <div className="form-group" style={{ width: "120px" }}>
            <label>Count</label>
            <input type="number" value={count} onChange={(e) => setCount(Number(e.target.value))} min={1} max={50} />
          </div>
        </div>
        <button type="submit" className="btn btn-primary" disabled={searching}>
          {searching ? "Searching..." : "🔍 Find Contacts"}
        </button>
      </form>

      {error && <div className="card" style={{ marginBottom: "1rem", border: "1px solid #fecaca", background: "#fef2f2", color: "#991b1b" }}>{error}</div>}

      {results.length > 0 && (
        <>
          <div className="card" style={{ marginBottom: "1rem" }}>
            <p style={{ margin: "0 0 0.75rem 0", fontWeight: 600 }}>{summary}</p>
            <div className="inline-form">
              <div className="form-group">
                <select className="filter-select" value={selectedList} onChange={(e) => setSelectedList(e.target.value)}>
                  <option value="">Select list to import to...</option>
                  {lists.map((l: any) => <option key={l.id} value={l.id}>{l.name}</option>)}
                </select>
              </div>
              <button className="btn btn-primary" onClick={handleImport} disabled={!selectedList || importing}>
                {importing ? "Importing..." : `Import ${results.length} contacts`}
              </button>
            </div>
            {importResult && (
              <p style={{ margin: "0.5rem 0 0 0", fontSize: "0.85rem", color: "#166534" }}>
                ✅ Imported: {importResult.imported}, Skipped: {importResult.skipped}
              </p>
            )}
          </div>

          <div className="table-container">
            <table className="data-table">
              <thead>
                <tr>
                  <th style={{ width: "30px" }}>#</th>
                  <th>Email</th>
                  <th>Name</th>
                  <th>Company</th>
                  <th>Title</th>
                  <th>Source</th>
                </tr>
              </thead>
              <tbody>
                {results.map((c, i) => (
                  <tr key={i}>
                    <td style={{ color: "#94a3b8", fontSize: "0.8rem" }}>{i + 1}</td>
                    <td>{c.email}</td>
                    <td>{c.name || "—"}</td>
                    <td>{c.company || "—"}</td>
                    <td style={{ fontSize: "0.8rem", maxWidth: "200px", overflow: "hidden", textOverflow: "ellipsis" }}>{c.title || "—"}</td>
                    <td style={{ fontSize: "0.75rem", maxWidth: "200px", overflow: "hidden", textOverflow: "ellipsis" }}>{c.source || "—"}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}
    </main>
  );
}
